clk: renesas: Use priv_auto_alloc_size for R8A779A0 clock driver
Reinstate priv_auto_alloc_size for R8A779A0 clock driver since
priv_auto member has not been available yet on U-Boot v2010.10

This fixes following build error:
r8a779a0-cpg-mssr.c:296:3: error: ‘struct driver’ has no member named
‘priv_auto’

Signed-off-by: Hai Pham <hai.pham.ud@renesas.com>